version = 1

test_patterns = ["test-*.js"]

exclude_patterns = [
    ".extra/**",
    ".github/**",
    "docs/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "jest"
  ]
  dialect = "typescript"